- name: Remove Kotlin LSP
  shell: rm -rf ~/kotlin-language-server
  tags:
    - install
    - kotlin-language-server
- name: Clone kotlin-language-server
  ansible.builtin.git:
    repo: 'https://github.com/fwcd/kotlin-language-server.git'
    dest: "{{ lookup('env', 'HOME') }}/kotlin-language-server"
    # version: release-0.7
  tags:
    - install
    - kotlin-language-server
- name: Build kotlin-language-server
  shell: "cd {{ lookup('env', 'HOME') }}/kotlin-language-server && ./gradlew :server:installDist"
  tags:
    - install
    - kotlin-language-server
